#!/bin/sh

# Add Some Static Devices
mknod -m 666 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 666 /dev/random c 1 8
mknod -m 666 /dev/urandom c 1 9

# PTS Subsystem
mkdir /dev/pts
mount -t devpts devpts /dev/pts

# SHM Subsystem
mkdir /dev/shm
mount -t tmpfs none /dev/shm

# Populate with mdev
mdev -s

# Monitor with mdev
echo /sbin/mdev > /proc/sys/kernel/hotplug
